var arrLang = {
    'br' : {
        'perfil': 'Perfil',
        'portfolio': 'Portfolio',
        'habilidades': 'Habilidades',
        'cartaovisita': 'Cartão de visita',
        'testemunhas': 'Testemunhas',
        'prof-sobremim': 'Sobre mim',
        'prof-sobremim-desc': 'Olá :) , Tenho 24 anos, e sou um verdadeiro entusiasta da programação. Tive contato com computação muito cedo e desde então essa paixão vem crescendo. Então resolvi expandir meu conhecimento, não ficando apenas na área de Administração, no qual tenho experiência (e também amo), mas querendo construir mais para meu portfólio e agregar nas empresas que almejo.',
        'prof-grid1': 'Anos de Experiência',
        'prof-grid2': 'Projetos feitos',
        'prof-grid3': 'Clientes Felizes',
        'prof-grid4': 'Seguidores nas Mídias',
        'prof-oquefaco': 'O que eu faço',
        'prof-webdesigner': 'Desenvolvedor Web',
        'prof-webdesigner2': 'Uma solução que atende todos os tipos de plataforma que se conecta a internet, ideal por lidar bem com sistemas mais robustos e viabilizar a distribuição / descentralização de armazenamento de dados',
        'prof-deskdev': 'Desenvolvedor Desktop',
        'prof-deskdev2': 'Achou que teriamos só soluções web? Temos soluções em desktop tambem, afim de complementar a gama de usabilidade de sua aplicação',
        'prof-uiux': 'Minimalista? Ilustrações na tela principal? Vamos construir o melhor modelo de interface do usuário para fornecer a melhor experiência possível de navegação!',
        'foot2-title': 'Mídias Sociais',
        'foot3-title': 'Normas',
        'foot3-pol': 'Políticas de Privacidade',
        'foot4-title': 'Apoio',
        'copy': 'CopyRight © 2021  THE KINGS, DIREITOS RESERVADOS',
        'devel': 'Desenvolvido por',
        'termos-title': 'Política de Segurança e Privacidade',
        'termos': 'A Política de Segurança e Privacidade da THE KINGS SERVICES foi criada para demonstrar o compromisso da Companhia com a segurança e a privacidade de informações coletadasdos usuários de serviços interativos aqui disponíveis. Investidores e analistas podem visitar este website e conhecer os serviços e produtos que a THE KINGS SERVICES oferece, ler relatórios, obter informações e notícias, sem fornecer informações pessoais. Caso você forneça alguma informação, esta Política procura esclarecer como a THE KINGS SERVICES coleta e trata suas informações individuais. Esta Política de Segurança e Privacidade está sujeita a alterações de tempos em tempos.',
        'termos2': '1. Quaisquer informações que os usuários passarem serão coletadas e guardadas de acordo com padrões rígidos de segurança e confidencialidade. Contudo, devido ao atual estado de desenvolvimento tecnológico, não podemos garantir segurança absoluta para suas informações pessoais.',
        'termos3': '2. As informações pessoais que forem passadas à Companhia pelos usuários serão coletadas por meios éticos e legais, podendo ter um ou mais propósitos, sobre os quais os usuários serão informados.',
        'termos4': '3. Os usuários serão avisados de quais informações suas estarão sendo coletadas antes do instante dessa coleta, ficando a opção de escolha para fornecimento ou não dessas informações sob responsabilidade do usuário, o qual também terá ciência das consequências de sua decisão.',
        'termos5': '4. A menos que a THE KINGS SERVICES  receba determinação legal ou judicial, suas informações nunca serão transferidas a terceiros ou usadas para finalidades diferentes daquelas para as quais foram coletadas.',
        'termos6': '5. A Companhia manterá íntegras as informações que forem fornecidas pelos usuários.',
        'termos7': '6. Este website contem links ou frames de outros sites, que podem ou não ser parceiros da Companhia. Esses links e frames são disponibilizados buscando, tão somente, proporcionar mais um benefício para os usuários. Vale ressaltar que a inclusão desses links e frames não significa que a THE KINGS SERVICES  tenha conhecimento, concorde ou seja responsável por eles ou por seus respectivos conteúdos. Você deverá consultar as políticas de privacidade dos outros websites, uma vez que não temos controle sobre informação que é submetida ou coletada por tais terceiros.',
        'termos8': '7. Para fins administrativos, eventualmente a Companhia poderá utilizar “cookies”(*), sendo que o usuário pode, a qualquer instante, ativar em seu navegador mecanismos para informá-lo quando os mesmos estiverem acionados ou para evitar que sejam acionados.',
        'termos9': '8. Recomenda-se a verificação desta Política de Segurança e Privacidade e os outros termos legais aqui contidos sempre que você acessar ou utilizar este website.',
    },
    'en' : {
        'perfil': 'Profile',
        'portfolio': 'Portfolio',
        'habilidades': 'Skills',
        'cartaovisita': 'Business Card',
        'testemunhas': 'Testimonials',
        'prof-sobremim': 'About me',
        'prof-sobremim-desc': "Hi :) , I'm 24 years old, and I'm a real programming enthusiast. I had contact with computing very early and since then this passion has been growing. So I decided to expand my knowledge, not just staying in the Administration area, in which I have experience (and I also love it), but wanting to build more for my portfolio and add to the companies that i want.",
        'prof-grid1': 'Years Experience',
        'prof-grid2': 'Projects Done',
        'prof-grid3': 'Happy Clients',
        'prof-grid4': 'Followers in SM',
        'prof-oquefaco': 'What i do?',
        'prof-webdesigner': 'Web Designer',
        'prof-webdesigner2': 'A solution that meets all types of platforms that connect to the internet, ideal for dealing well with more robust systems and enabling a distribution/decentralization of data storage',
        'prof-deskdev': 'Desktop Developer',
        'prof-deskdev2': 'Did you think we would only have web solutions? We also have desktop solutions, in order to complement the usability range of your application.',
        'prof-uiux': "Minimalist? Illustrations on the main screen? Let's build the best UI model to provide the best possible browsing experience!",
        'serv1-title': 'Vehicle Transport',
        'serv2-title': 'Car Buying and Selling',
        'serv1-desc': 'Vehicle transport is characterized by take vehicles appropriately and legally to other places, cities or states.',
        'serv2-desc': 'This investment is characterized by: the investor buys the car with us, and the kings services propriately and legally, bringing the traded profitability to the investor.',
        'donos': 'TKS Motors',
        'soc1-desc': 'TKS CEO and investor, Brazilian, businessman, has 17 stores currently in the Brazil and an administration office that manages its chain of stores.',
        'soc2-desc': 'CEO and investor of TKs, Brazilian with American citizenship, entrepreneur, accredited to buy and sell vehicles in the USA. It currently has more than 50 investment vehicles in the USA.',
        'depo1': "Some time ago known Alcir through a friend, who soon found out with whom he works. At first I was a little unsure, but I got into the business. Today, I already got the value of my investment and I am one of TKS's investors. I never had any problems and they were always very transparent with me. And I don't even live in the USA.",
        'depo2': "I am a customer of TKS, I bought a car with them, and everything that was passed on to me, really is a reality. Very good to work with people like that. In fact, I'm Brazilian, but I live in the USA, and it's hard to find people who do honest work.",
        'foot1-title': 'Services',
        'foot1-serv1': 'Vehicle Transport',
        'foot1-serv2': 'Car Buying and Selling',
        'foot2-title': 'Social Media',
        'foot3-title': 'Rules',
        'foot3-pol': 'Privacy Policy',
        'foot4-title': 'Support',
        'copy': 'CopyRight © 2021  THE KINGS, All rights reserved.',
        'devel': 'Development by',
        'termos-title': 'Security and Privacy Policy',
        'termos': "THE KINGS SERVICES 'Security and Privacy Policy was created to demonstrate the Company's commitment to security and the privacy of information collected from users of interactive services available here. Investors and analysts can visit this website and learn about the services and products that THE KINGS SERVICES offers, read reports, obtain information and news, without providing personal information. If you provide any information, this Policy seeks to clarify how the THE KINGS SERVICES collects and treats your individual information. This Security and Privacy Policy is subject to change from time to time.",
        'termos2': '1. Any information that users pass on will be collected and stored in accordance with strict security and confidentiality standards. However, due to the current state of technological development, we cannot guarantee absolute security for your personal information.',
        'termos3': '2. Personal information that is passed on to the Company by users will be collected by ethical and legal means, and may have one or more purposes, about the which users will be informed.',
        'termos4': '3. Users will be notified of what information is being collected before the time of such collection, leaving the option to choose to supply or not of this information under the responsibility of the user, who will also be aware of the consequences of his decision.',
        'termos5': '4. Unless THE KINGS SERVICES receives legal or judicial determination, your information will never be transferred to a third party or used for any purpose different from those for which they were collected.',
        'termos6': '5. The Company will keep the information provided by the users intact.',
        'termos7': '6. This website contains links or frames from other sites, which may or may not be partners of the Company. These links and frames are made available seeking, as only, provide one more benefit to users. It is worth mentioning that the inclusion of these links and frames does not mean that THE KINGS SERVICES has knowledge, responsible for them or their respective contents. You should consult the privacy policies of the other websites, as we have no control over information that is submitted or collected by such third parties.',
        'termos8': '7. For administrative purposes, the Company may eventually use "cookies" (*), and the user can, at any time, activate in his browser mechanisms to inform you when they are triggered or to prevent them from being triggered.',
        'termos9': '8. It is recommended to check this Security and Privacy Policy and the other legal terms contained herein whenever you access or use this website.',
    },
    'es' : {
        'perfil': 'Perfil',
        'portfolio': 'Portfolio',
        'habilidades': 'Habilidades',
        'cartaovisita': 'tarjeta de visita',
        'testemunhas': 'Testimonios',
        'prof-sobremim': 'Sobre mí',
        'prof-sobremim-desc': 'Hola :), tengo 24 años y soy un verdadero entusiasta de la programación. Tuve contacto con la informática muy temprano y desde entonces esta pasión ha ido creciendo. Así que decidí ampliar mis conocimientos, no solo quedándome en el área de Administración, en la que tengo experiencia (y también me encanta), sino queriendo construir más para mi cartera y sumar a las empresas que quiero.',
        'prof-grid1': 'Años de experiencia',
        'prof-grid2': 'Proyectos Realizados',
        'prof-grid3': 'Clientes Felices',
        'prof-grid4': 'Seguidores en MS',
        'prof-oquefaco': '¿Lo que hago?',
        'prof-webdesigner': 'Diseñador web',
        'prof-webdesigner2': 'Una solución que cumple con todos los tipos de plataformas que se conectan a Internet, ideal para tratar bien con sistemas más robustos y permitir una distribución/descentralización del almacenamiento de datos',
        'prof-deskdev': 'Desarrollador de escritorio',
        'prof-deskdev2': '¿Pensabas que solo tendríamos soluciones web? También contamos con soluciones de escritorio, con el fin de complementar el rango de usabilidad de su aplicación.',
        'prof-uiux': '¿Minimalista? ¿Ilustraciones en la pantalla principal? ¡Construyamos el mejor modelo de interfaz de usuario para brindar la mejor experiencia de navegación posible!',
        'serv1-title': 'Transporte de vehículos',
        'serv2-title': 'Compra y venta de autos',
        'serv1-desc': 'El transporte de vehículos se caracteriza por llevar los vehículos adecuadamente y legalmente a otros lugares, ciudades o estados.',
        'serv2-desc': 'Esta inversión se caracteriza por: el inversionista compra el auto con nosotros y The Kings Services negociar de manera adecuada y legal llevando la rentabilidad negociada al inversor.',
        'donos': 'Los Motores da TKS',
        'soc1-desc': 'El CEO e inversor de TKS, empresario brasileño, tiene 17 tiendas actualmente en el Brasil y una oficina administrativa que gestiona su cadena de tiendas. y otros negocios.',
        'soc2-desc': 'CEO e inversor de conocimientos tradicionales, brasileño con ciudadanía estadounidense, empresario, acreditado para comprar y vender vehículos en los Estados Unidos. Actualmente cuenta con más de 50 vehículos de inversión en los Estados Unidos.',
        'depo1': 'Hace algún tiempo conocido o Alcir a través de un amigo, que pronto descubrió con quién trabaja. Al principio estaba un poco inseguro, pero me metí en el negocio. Hoy, ya obtuve el valor de mi inversión y soy uno de los inversores de TKS. Nunca tuve ningún problema y siempre fueron muy transparentes conmigo. Y ni siquiera vivo en los Estados Unidos.',
        'depo2': 'Soy cliente de TKS, compré un auto con ellos, y todo lo que me pasó, realmente es una realidad. Muy bueno trabajar con gente así. De hecho, soy brasileño pero vivo en los Estados Unidos, y es difícil encontrar personas que hagan un trabajo honesto.',
        'foot1-title': 'Servicios',
        'foot1-serv1': 'Transporte de vehículos',
        'foot1-serv2': 'Compra y venta de autos',
        'foot2-title': 'Medios sociales',
        'foot3-title': 'Reglas',
        'foot3-pol': 'Política de privacidad',
        'foot4-title': 'Apoyo',
        'copy': 'CopyRight © 2021  THE KINGS, Todos los derechos reservados',
        'devel': 'Desarrollo por',
        'termos-title': 'Política de seguridad y privacidad',
        'termos': 'La Política de Seguridad y Privacidad de THE KINGS SERVICES fue creada para demostrar el compromiso de la Compañía con la seguridad y la privacidad de la información recopilada de los usuarios de los servicios interactivos disponibles aquí. Los inversores y analistas pueden visitar este sitio web y conocer los servicios y productos que THE KINGS SERVICES ofrece, lee informes, obtiene información y noticias, sin proporcionar información personal. Si proporciona alguna información, esta Política busca aclarar cómo THE KINGS SERVICES recopila y trata su información individual. Esta Política de seguridad y privacidad está sujeta a cambios ocasionales.',
        'termos2': '1. Cualquier información que los usuarios transmitan será recopilada y almacenada de acuerdo con estrictos estándares de seguridad y confidencialidad. Sin embargo, debido a la estado actual de desarrollo tecnológico, no podemos garantizar la seguridad absoluta de su información personal.',
        'termos3': '2. La información personal que los usuarios transmiten a la Compañía se recopilará por medios éticos y legales, y puede tener uno o más propósitos sobre qué usuarios serán informados.',
        'termos4': '3. Los usuarios serán notificados de la información que se recopila antes del momento de dicha recopilación, dejando la opción de elegir suministrar o no de esta información bajo la responsabilidad del usuario, quien también estará al tanto de las consecuencias de su decisión.',
        'termos5': '4. A menos que THE KINGS SERVICES reciba una determinación legal o judicial, su información nunca será transferida a un tercero o utilizada para ningún propósito diferentes de aquellos para los cuales fueron recolectados.',
        'termos6': '5. La Compañía mantendrá intacta la información provista por los usuarios.',
        'termos7': '6. Este sitio web contiene enlaces o marcos de otros sitios, que pueden o no ser socios de la Compañía. Estos enlaces y marcos están disponibles buscando, como solo, brinde un beneficio más a los usuarios. Vale la pena mencionar que la inclusión de estos enlaces y marcos no significa que THE KINGS SERVICES tenga conocimiento, responsable de ellos o de sus respectivos contenidos. Debe consultar las políticas de privacidad de los otros sitios web, ya que no tenemos control sobre la información que se envía o recogido por dichos terceros.',
        'termos8': '7. Para fines administrativos, la Compañía puede eventualmente usar "cookies" (*), y el usuario puede, en cualquier momento, activar en su navegador mecanismos para informarle cuándo se activan o para evitar que se activen.',
        'termos9': '8. Se recomienda consultar esta Política de seguridad y privacidad y los demás términos legales contenidos en este documento cada vez que acceda o use este sitio web.',
    }
};

$(function() {
    $('.translate').click(function() {
        var lang = $(this).attr('id');

        $('.lang').each(function(index, item){
            $(this).text(arrLang[lang][$(this).attr('key')]);
        });
    });
});